### ISSUE TITLE
Github Action not producing Build due to compilation Errors

### ISSUE THREAD

**Issue by theAkito** [fossable/goldboot#26]
Greetings! 👋🏻 

https://github.com/goldboot/goldboot/runs/7383149835?check_suite_focus=true#step:5:1055

Could these compilation errors in the CI build please be fixed?

Trying to build the project locally based on the repository's content and the Github Action CI definition was successless.
It would be great, if it would be possible for anyone to build the project.

**Comment by cilki** [comment]
I'm in the middle of a couple of major changes:
- Revise the image format to support encryption
- Revise the configuration format to use YAML instead of JSON

Usually I'd create a new branch to avoid breaking the build, but this thing is still pretty early on, so nothing is stable yet. Right now I'm looking for more feedback on the ideas rather than the implementation.

That said, I'm hoping to fix everything I broke in the next few weeks :smiley:.

**Comment by theAkito** [comment]
I see now, that's great. 🙂 

When I opened this issue, I guessed you were having it build locally, but didn't bother to fix the repository's CI build, yet. (Sometimes happens to me...)

If you have running it locally, you could perhaps share the compiler version and dependencies you use.

If you don't have it running locally, then I would probably tinker around with it myself, however I'm now not sure how much sense that would make, if you are in the process of applying major changes. 🤔

**Comment by cilki** [comment]
> That said, I'm hoping to fix everything I broke in the next few weeks

Still haven't gotten to this yet, but I didn't forget!

**Comment by dmgolembiowski** [comment]
Hey @cilki I've had my eye on this project for multiple months and I think I'd like to start contributing. Would you have the time to put together a `CONTRIBUTING.md` or other guide for collaborators to help out this project?

**Comment by theAkito** [comment]
@dmgolembiowski That'd be great!

**Comment by cilki** [comment]
@dmgolembiowski That sounds great! I'll see what I can do on documentation.

It also depends on what your interests/experiences are. If you're good with APIs, the `goldboot-registry` crate is really under developed and would probably be a good place to start. Think of it like a Docker registry where you can push/pull/list images over HTTPS except the [image format is custom](https://github.com/fossable/goldboot/blob/master/goldboot/src/image.rs) instead of OCI. (That image format, if I recall, should be nearly 100% complete, but more tests would be welcome).

The `goldboot` crate itself still needs a bit of work before it's contributor friendly. I recall I was held up on the design [surrounding the provisioners](https://github.com/fossable/goldboot/blob/master/goldboot/src/provisioners.rs) last year which is a critical component. Now that some time has passed, I should have fresh eyes on that quandary. Once that's done and I fix the remaining build issues, there should be lots of opportunity for contributors.

Sorry to everyone for leaving this one hanging for so long!

**Comment by cilki** [comment]
Although the tests still aren't fully working, at least the build is fixed now.

**Comment by cilki** [comment]
@dmgolembiowski by the way, if you use Windows or macOS, there are a couple platform-specific cases I can't test on Linux. Would be a good place to start contributing.

**Comment by dmgolembiowski** [comment]
oh cool
